In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [5]:
import numpy as np
a1 = np.array([[1, 2], [3,4]])
print(a1)

[[1 2]
 [3 4]]


In [7]:
import numpy as np
a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
print(type(a2))

<class 'numpy.ndarray'>


In [10]:
print(a.shape)

(3,)


In [11]:
b = np.array([[1, 2, 3], [4,5,6]])

In [12]:
print(b.shape)

(2, 3)


In [13]:
print(b.data)

In [14]:
print(b.dtype)

int32


In [15]:
b1 = np.array([[1.2, 2.1, 3.4],[1.0, 2.3, 3.5]])

In [19]:
print(b1.dtype)

float64


In [20]:
import numpy as np
a3= np.array([[1,2,3],[4,5,6]])
print(a3.shape)

(2, 3)


In [21]:
a4= np.arange(24)
print(a4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [22]:
a5 = np.array([1,2,3,4,5], dtype= np.float32)
print(a5.itemsize)

4


In [23]:
print(a5.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [24]:
a6 = np.empty([3,2], dtype=int)

In [25]:
print(a6)

[[ 111411296          0]
 [ 156190688          0]
 [ 543519841 1144201313]]


In [26]:
a7 = np.zeros((2,3), dtype=np.int)


In [27]:
print(a7)

[[0 0 0]
 [0 0 0]]
