In [2]:
import numpy as np
x = np.array([[1,2], [3, 4], [5,6]])
y = x[[0,1,2], [0,1,0]]
print(y)

#(0,0), (1,1), (2,0)
# 4 x 3


[1 4 5]


In [3]:
import numpy as np
x1 = np.array([[0,1,2],[3, 4, 5], [6, 7, 8],[9, 10, 11]])
print(x1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
z = x1[1:4, 1:3]
print(z)

[[ 4  5]
 [ 7  8]
 [10 11]]


In [12]:
import numpy as np
x2 = np.array([[0,1,2],[3, 4, 5], [6, 7, 8],[9, 10, 11]])
print(x2)
rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])

y3 = x2[rows, cols]
print("")
print(y3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  2]
 [ 9 11]]


In [19]:
import numpy as np
a10 = np.arange(10)
print(a10)
print(a10[2:])
print(a10[:8])
print(a10[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[2 3 4]


In [29]:
import numpy as np
a11 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a11)
print("----")
print(a11[:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
import numpy as np
a12 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a12)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a12[...,1]

array([2, 5, 8])

In [39]:
a12[1,...]

array([4, 5, 6])

In [40]:
a12[...,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])