In [6]:
import numpy as np
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [8]:
import numpy as np
x1 = np.arange(5, dtype = float)
print(x1)

[0. 1. 2. 3. 4.]


In [5]:
import numpy as np
x2 = np.arange(10, 20, 2)
print(x2)

[10 12 14 16 18]


In [9]:
import numpy as np
x3 = np.arange(10)
print(x3)
s = slice(2,7,2)
print(x3[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [10]:
import numpy as np
x4 = np.arange(10)
print(x4)
s2 = x4[2:7:2]
print(x3[s2])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [12]:
import numpy as np
x5 = np.arange(10)
print(x5)
print(x5[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
