In [2]:
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(a.shape)
a1 = a[1:4, 1:3]
print(a1)
a2 = a[1:4,[1,2]]
print(a2)


(4, 3)
[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [3]:
a3 = a[a > 5]
print(a3)


[ 6  7  8  9 10 11]


In [4]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [ ]:
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b1 = 