In [3]:
import numpy as np
a = np.arange(0,60,5)
print(a)
print(a.shape)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
(12,)


In [7]:
a1 = a.reshape(3, 4)
print(a1.shape)
print(a1)
for x in np.nditer(a1): 
    print(x)

(3, 4)
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [16]:
# 1d -> 2d
import numpy as np
a2 = np.array([10, 11, 12, 13, 14])
print(a2.shape)
a3 = a2.reshape(a2.shape[0], 1)
print(a3.shape)
# 2d -> 3d
a4 = np.array([[10,11], [12, 13], [14, 15]])
print(a4.shape)
a5 = a3.reshape(a4.shape[0], a4.shape[1], 1)
print(a5.shape)

(5,)
(5, 1)
(3, 2)


ValueError: cannot reshape array of size 5 into shape (3,2,1)