In [6]:
import numpy as np
x = np.array([[1,2,3],[3,4,5],[6,7,8], [9,10,11]])
print(x.shape)
print(x)
rows = np.array([[0,0],[3,3]])
columns = np.array([[0,2],[1,0]])
y = x[rows, columns]
print(y)
y1 = x[1:4, 1:3]


(4, 3)
[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1  3]
 [10  9]]
