In [2]:
import numpy as np
a = np.empty([3, 2], dtype=int)
print(a)

[[1097072700  693764228]
 [1130644068  710541444]
 [1164199012  727318660]]


In [6]:
a1 = np.zeros([3, 2], dtype=np.float64)
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
a2 = np.ones([3, 2], dtype=int)
print(a2)

[[1 1]
 [1 1]
 [1 1]]


In [9]:
a3 = np.asarray([1, 2, 3], dtype=np.float32)
print(a3)

[1. 2. 3.]


In [10]:
a4 = np.arange(5)
print(a4)

[0 1 2 3 4]


In [11]:
a5 = np.arange(1, 10, 2)
print(a5)

[1 3 5 7 9]


In [24]:
import numpy as np
a6 = np.arange(10)
print(a6)
s6 = slice(2,7,2)
print(s6)
print(a6[s6])
print(a6[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]
[2 4 6]


In [28]:
a7 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a8 = np.array(a7)
print(a8.shape)
print(a8[1:,:-1])


(3, 3)
[[4 5]
 [7 8]]


In [37]:
a9 = np.array([[1, 2], [2, 3], [4, 5]])
print(a9.shape)
print(a9[2])
a10 = a9[[0,1,2], [0,1,0]]
print(a10)

(3, 2)
[4 5]
[1 3 4]


In [40]:
a11 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 10]])
print(a11.shape)

r11 = np.array([[0,0],[3,3]])
c11 = np.array([[0,2],[0,2]])

result = a11[r11, c11]
print(result)

(4, 3)
[[ 0  2]
 [ 9 10]]
