In [8]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)
type(a)
print(a[-1])
print(a[-4])
print(a[1:2])

[1 2 3 4]
4
1
[2]


In [19]:
data = [[2, 3, 4],[5,6,7]]
a1 = np.array(data)
print(a1)
type(a1)
print(a1[0][0])
print(a1[0][1])
print(a1[1][0])
print(a1[0,0])
print(a1[1:2])
print(a1[0,])
print(a1[-2:])



[[2 3 4]
 [5 6 7]]
2
3
5
2
[[5 6 7]]
[2 3 4]
[[2 3 4]
 [5 6 7]]


In [22]:
import numpy as np
data = [[2, 3, 4],[5, 6, 7],[8, 9, 10]]
a3 = np.array(data)
print(a3.shape)
x1 = a3[:, :-1]
print(x1)

(3, 3)
[[2 3]
 [5 6]
 [8 9]]
