In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
a1 = np.array([[1, 2], [3, 4]])
print(a1)

[[1 2]
 [3 4]]


In [7]:
a2 = np.array([1,2,3,4], ndmin = 2)
print(a2)

[[1 2 3 4]]


In [9]:
a3 = np.array([1,2,3,4], ndmin=3)
print(a3)

[[[1 2 3 4]]]


In [12]:
a4 = np.dtype(np.int32)
print(a4)
a5 = np.array([1, 2, 3], dtype = complex)
print(a5)

int32
[1.+0.j 2.+0.j 3.+0.j]
