In [3]:
import numpy as np
a = np.arange(0,60,5)
print(a)
print(a.shape)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
(12,)


In [7]:
a1 = a.reshape(3, 4)
print(a1.shape)
print(a1)
for x in np.nditer(a1): 
    print(x)

(3, 4)
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [18]:
# 1d -> 2d
import numpy as np
a2 = np.array([10, 11, 12, 13, 14])
print(a2.shape)
a3 = a2.reshape(a2.shape[0], 1)
print(a3.shape)
# 2d -> 3d
a4 = np.array([[10,11], [12, 13], [14, 15]])
print(a4.shape)
a5 = a4.reshape((a4.shape[0], a4.shape[1], 1))
print(a5.shape)

(5,)
(5, 1)
(3, 2)
(3, 2, 1)


In [27]:
# boolean indexing
names = np.array(['Tom', 'Joe', 'Will', 'Thomas'])
data = np.random.randn(7, 4)
#print(names)
#print(data)
names == 'Tom'
names != 'Tom'
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.06930616, 1.68252128, 2.05091894, 1.21065261],
       [0.        , 0.17476703, 0.08241433, 0.12966738],
       [0.87026145, 0.        , 0.        , 0.        ],
       [0.5492264 , 0.        , 0.02842844, 0.13576575],
       [0.56761414, 0.        , 0.16897945, 0.        ],
       [1.56300025, 1.4649133 , 0.68117862, 0.        ]])

In [32]:
arr = np.empty((8,4))
#print(arr)
for i in range(8):
    arr[i] = i
#arr
#arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [36]:
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)

[ 1.25194891 -0.45193232 -0.86127297  0.10302908 -0.72533577  0.34674227]
[-0.86127297 -0.72533577 -0.45193232  0.10302908  0.34674227  1.25194891]
