In [12]:
import numpy as np
import csv
data = np.loadtxt("numpy_data.csv", delimiter=',', skiprows=2)
print(data)
data[:,:2]

[[ 1.          0.88845837  0.21370612  0.4919565 ]
 [ 2.          0.56817447  0.61363956  0.17227638]
 [ 3.          0.56024969  0.68163566  0.51237708]
 [ 4.          0.15528457  0.74950444  0.4995597 ]
 [ 5.          0.78796339  0.21835737  0.22937796]
 [ 6.          0.71616586  0.83032344  0.21190183]
 [ 7.          0.87086615  0.07615078  0.67658666]
 [ 8.          0.6967517   0.73512143  0.72976436]
 [ 9.          0.42947289  0.23594083  0.70472627]
 [10.          0.41416397  0.68295541  0.36719596]
 [11.          0.97869349  0.59200144  0.05129855]
 [12.          0.77641082  0.16407058  0.29474843]
 [13.          0.93541419  0.35107144  0.65239285]
 [14.          0.92015285  0.73558359  0.57026366]
 [15.          0.364472    0.08949353  0.53026277]
 [16.          0.769254    0.26652379  0.15800702]
 [17.          0.66539313  0.35265765  0.06617042]
 [18.          0.77536458  0.96295861  0.93555429]
 [19.          0.83846772  0.98465766  0.89300263]
 [20.          0.15428763  0.07

array([[ 1.        ,  0.88845837],
       [ 2.        ,  0.56817447],
       [ 3.        ,  0.56024969],
       [ 4.        ,  0.15528457],
       [ 5.        ,  0.78796339],
       [ 6.        ,  0.71616586],
       [ 7.        ,  0.87086615],
       [ 8.        ,  0.6967517 ],
       [ 9.        ,  0.42947289],
       [10.        ,  0.41416397],
       [11.        ,  0.97869349],
       [12.        ,  0.77641082],
       [13.        ,  0.93541419],
       [14.        ,  0.92015285],
       [15.        ,  0.364472  ],
       [16.        ,  0.769254  ],
       [17.        ,  0.66539313],
       [18.        ,  0.77536458],
       [19.        ,  0.83846772],
       [20.        ,  0.15428763]])

In [13]:
names = ["xdata", "y1", "y2", "y3"]
data3 = np.genfromtxt("numpy_data.csv", dtype=None, delimiter=',', names = names, skip_heade)